services:
  publisher:
    build:
      context: ..
      dockerfile: ./publisher/Dockerfile
    restart: on-failure:5
    # depends_on:
    #   rabbitmq:
    #     condition: service_healthy
    # links: 
    #   - rabbitmq
    volumes:
      - ./index.ts:/usr/src/app/index.ts
      - ../node_modules:/usr/src/app/node_modules
    environment:
      TO_USERNAME: "rmuser"
      TO_PASSWORD: "rmpassword"
      TO_HOSTNAME: "rabbitmq"
      TO_PORT: "5672"
      TO_QUEUE: "inbox"
      TO_EXCHANGE: "inbox"
      TO_ROUTINGKEY: "gen"
      COUNT: "1"
      SLEEP: "1000"
    networks:
      - rabbitmq-share-net

networks:
  rabbitmq-share-net:
    external: true
