services:
  consumer:
    build:
      context: ..
      dockerfile: ./1.consumer/Dockerfile
    restart: on-failure:5
    # depends_on:
    #   rabbitmq:
    #     condition: service_healthy
    # links: 
    #   - rabbitmq
    volumes:
      - ./index.ts:/usr/src/app/index.ts
      - ../node_modules:/usr/src/app/node_modules
    environment:
      FAIL: "false"
      REJECTALL: "true"
      SLEEP: "500"
      FROM_USERNAME: "rmuser"
      FROM_PASSWORD: "rmpassword"
      FROM_HOSTNAME: "rabbitmq"
      FROM_PORT: "5672"
      FROM_QUEUE: "inbox"
      FROM_EXCHANGE: "inbox"
      FROM_ROUTINGKEY: "gen"
      RETRY_QUEUE: "true"
      RETRY_QUEUE_TTL: "5000"
      PREFETCH: "1"
    networks:
      - rabbitmq-share-net

networks:
  rabbitmq-share-net:
    external: true
