services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 1s
      retries: 20
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ../rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - 15672:15672
    networks:
      - rabbitmq-share-net

  publisher:
    build:
      context: ..
      dockerfile: ./local-publisher/Dockerfile
    restart: on-failure:5
    hostname: rabbitmq-external
    depends_on:
      rabbitmq:
        condition: service_healthy
    links: 
      - rabbitmq
    volumes:
      - ./index.ts:/usr/src/app/index.ts
      - ../node_modules:/usr/src/app/node_modules
    env_file:
      - .env
    networks:
      - rabbitmq-share-net

networks:
  rabbitmq-share-net:
    external: true
